#!/bin/sh
# SPDX-License-Identifier: LGPL-3.0-or-later
#
# Copyright (C) 2023 Perry Werneck <perry.werneck@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

echo "menuentry '${install-label}' --class gnu-linux --class gnu --class os \$menuentry_id_option 'gnulinux-test-${install-version}-install-boot' {"
echo "    load_video"
echo "    set gfxpayload=keep"
echo "    insmod gzio"
echo "    insmod part_gpt"
echo "    insmod btrfs"
echo "    insmod search"  
echo "    insmod part_msdos"
echo "    insmod ext2"
echo ""
echo "    echo '${install-kloading} ...'"
echo "    linux	${kernel-fspath} ${kernel-parameters}"  
echo "    echo '${install-iloading} ...'"
echo "    initrd ${initrd-fspath}"
echo ""
echo " }"

exit 0

